--------------------------------------------------------
--  Fichier créé - mardi-novembre-02-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPETITIONS
--------------------------------------------------------

  CREATE TABLE "HELA"."COMPETITIONS" 
   (	"NUMERO" NUMBER, 
	"EQUIPE1" VARCHAR2(20 BYTE), 
	"EQUIPE2" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "HELA"."EMPLOYES" 
   (	"ID_E" NUMBER, 
	"NOME" VARCHAR2(20 BYTE), 
	"PRENOME" VARCHAR2(20 BYTE), 
	"EMPLACEMENT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOUER
--------------------------------------------------------

  CREATE TABLE "HELA"."JOUER" 
   (	"NUMERO" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table JOUEURS
--------------------------------------------------------

  CREATE TABLE "HELA"."JOUEURS" 
   (	"ID" NUMBER, 
	"ANNEES_NAISSANCE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"NATIONALITE" VARCHAR2(20 BYTE), 
	"TYPE_SPORT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPECTACLES
--------------------------------------------------------

  CREATE TABLE "HELA"."SPECTACLES" 
   (	"NUM" NUMBER, 
	"DUREE" FLOAT(126), 
	"HORAIRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------

  CREATE TABLE "HELA"."TICKETS" 
   (	"REFERENCE" NUMBER, 
	"NUM" NUMBER, 
	"DATEE" DATE, 
	"NOMT" VARCHAR2(20 BYTE), 
	"PRENOMT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HELA.COMPETITIONS
SET DEFINE OFF;
REM INSERTING into HELA.EMPLOYES
SET DEFINE OFF;
REM INSERTING into HELA.JOUER
SET DEFINE OFF;
REM INSERTING into HELA.JOUEURS
SET DEFINE OFF;
Insert into HELA.JOUEURS (ID,ANNEES_NAISSANCE,NOM,PRENOM,NATIONALITE,TYPE_SPORT) values (123,201,'dd','bb','dd','bb');
Insert into HELA.JOUEURS (ID,ANNEES_NAISSANCE,NOM,PRENOM,NATIONALITE,TYPE_SPORT) values (125,123,'202','dd','dd','ss');
Insert into HELA.JOUEURS (ID,ANNEES_NAISSANCE,NOM,PRENOM,NATIONALITE,TYPE_SPORT) values (111,2001,'moalla','hela','tunis','bcdbb');
REM INSERTING into HELA.SPECTACLES
SET DEFINE OFF;
REM INSERTING into HELA.TICKETS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index COMPETITIONS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELA"."COMPETITIONS_PK" ON "HELA"."COMPETITIONS" ("NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELA"."EMPLOYES_PK" ON "HELA"."EMPLOYES" ("ID_E") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index JOUER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELA"."JOUER_PK" ON "HELA"."JOUER" ("ID", "NUMERO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPECTACLES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELA"."SPECTACLES_PK" ON "HELA"."SPECTACLES" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TICKETS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HELA"."TICKETS_PK" ON "HELA"."TICKETS" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table COMPETITIONS
--------------------------------------------------------

  ALTER TABLE "HELA"."COMPETITIONS" ADD CONSTRAINT "COMPETITIONS_PK" PRIMARY KEY ("NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HELA"."COMPETITIONS" MODIFY ("EQUIPE2" NOT NULL ENABLE);
  ALTER TABLE "HELA"."COMPETITIONS" MODIFY ("EQUIPE1" NOT NULL ENABLE);
  ALTER TABLE "HELA"."COMPETITIONS" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "HELA"."EMPLOYES" ADD CONSTRAINT "EMPLOYES_PK" PRIMARY KEY ("ID_E")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HELA"."EMPLOYES" MODIFY ("EMPLACEMENT" NOT NULL ENABLE);
  ALTER TABLE "HELA"."EMPLOYES" MODIFY ("PRENOME" NOT NULL ENABLE);
  ALTER TABLE "HELA"."EMPLOYES" MODIFY ("NOME" NOT NULL ENABLE);
  ALTER TABLE "HELA"."EMPLOYES" MODIFY ("ID_E" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUER
--------------------------------------------------------

  ALTER TABLE "HELA"."JOUER" ADD CONSTRAINT "JOUER_PK" PRIMARY KEY ("ID", "NUMERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HELA"."JOUER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUER" MODIFY ("NUMERO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOUEURS
--------------------------------------------------------

  ALTER TABLE "HELA"."JOUEURS" MODIFY ("TYPE_SPORT" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUEURS" MODIFY ("NATIONALITE" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUEURS" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUEURS" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUEURS" MODIFY ("ANNEES_NAISSANCE" NOT NULL ENABLE);
  ALTER TABLE "HELA"."JOUEURS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPECTACLES
--------------------------------------------------------

  ALTER TABLE "HELA"."SPECTACLES" ADD CONSTRAINT "SPECTACLES_PK" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HELA"."SPECTACLES" MODIFY ("HORAIRE" NOT NULL ENABLE);
  ALTER TABLE "HELA"."SPECTACLES" MODIFY ("DUREE" NOT NULL ENABLE);
  ALTER TABLE "HELA"."SPECTACLES" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "HELA"."TICKETS" ADD CONSTRAINT "TICKETS_PK" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HELA"."TICKETS" MODIFY ("PRENOMT" NOT NULL ENABLE);
  ALTER TABLE "HELA"."TICKETS" MODIFY ("NOMT" NOT NULL ENABLE);
  ALTER TABLE "HELA"."TICKETS" MODIFY ("DATEE" NOT NULL ENABLE);
  ALTER TABLE "HELA"."TICKETS" MODIFY ("NUM" NOT NULL ENABLE);
  ALTER TABLE "HELA"."TICKETS" MODIFY ("REFERENCE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table JOUER
--------------------------------------------------------

  ALTER TABLE "HELA"."JOUER" ADD CONSTRAINT "IDE" FOREIGN KEY ("ID")
	  REFERENCES "HELA"."EMPLOYES" ("ID_E") ENABLE;
  ALTER TABLE "HELA"."JOUER" ADD CONSTRAINT "NUMC" FOREIGN KEY ("NUMERO")
	  REFERENCES "HELA"."COMPETITIONS" ("NUMERO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPECTACLES
--------------------------------------------------------

  ALTER TABLE "HELA"."SPECTACLES" ADD CONSTRAINT "IDEMP" FOREIGN KEY ("NUM")
	  REFERENCES "HELA"."EMPLOYES" ("ID_E") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKETS
--------------------------------------------------------

  ALTER TABLE "HELA"."TICKETS" ADD CONSTRAINT "IDEM" FOREIGN KEY ("REFERENCE")
	  REFERENCES "HELA"."EMPLOYES" ("ID_E") ENABLE;
  ALTER TABLE "HELA"."TICKETS" ADD CONSTRAINT "NUMEROC" FOREIGN KEY ("REFERENCE")
	  REFERENCES "HELA"."COMPETITIONS" ("NUMERO") ENABLE;
