--------------------------------------------------------
--  File created - Monday-November-29-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PRODUITCOSMETIQUE
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."PRODUITCOSMETIQUE" 
   (	"NUM" NUMBER, 
	"QRCODE" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"MARQUE" VARCHAR2(20 BYTE), 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OFFRE
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."OFFRE" 
   (	"CODE" NUMBER, 
	"PRIX" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"CIN_E" NUMBER, 
	"PHOTOS" VARCHAR2(225 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MATERIEL
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."MATERIEL" 
   (	"NOM" VARCHAR2(20 BYTE), 
	"COULEUR" VARCHAR2(20 BYTE), 
	"REFERENCE" NUMBER, 
	"ID_FOURNISEUR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FOURNISSEUR
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."FOURNISSEUR" 
   (	"ID" NUMBER(20,0), 
	"NUMTEL" NUMBER(20,0), 
	"NOM" VARCHAR2(20 BYTE), 
	"QUALITE" VARCHAR2(20 BYTE), 
	"CATEGORY" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(255 BYTE), 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYES
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."EMPLOYES" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"ROLE" VARCHAR2(20 BYTE), 
	"SALAIRE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "ISKANDER"."CLIENT" 
   (	"CIN" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"TEL" NUMBER, 
	"ADRESSE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into ISKANDER.PRODUITCOSMETIQUE
SET DEFINE OFF;
Insert into ISKANDER.PRODUITCOSMETIQUE (NUM,QRCODE,QUANTITE,NOM,MARQUE,PRIX) values (188,'fre',518,'qff','qf',518);
REM INSERTING into ISKANDER.OFFRE
SET DEFINE OFF;
Insert into ISKANDER.OFFRE (CODE,PRIX,TYPE,CIN_E,PHOTOS) values (15,159,'aa',185,null);
Insert into ISKANDER.OFFRE (CODE,PRIX,TYPE,CIN_E,PHOTOS) values (16,159,'aa',185,'C:/Users/Iskander/Pictures/Saved Pictures/wp7476062-msi-dragon-wallpapers.jpg');
REM INSERTING into ISKANDER.MATERIEL
SET DEFINE OFF;
Insert into ISKANDER.MATERIEL (NOM,COULEUR,REFERENCE,ID_FOURNISEUR) values ('aa','dd',15,1);
REM INSERTING into ISKANDER.FOURNISSEUR
SET DEFINE OFF;
Insert into ISKANDER.FOURNISSEUR (ID,NUMTEL,NOM,QUALITE,CATEGORY,EMAIL,ADRESSE) values (158,5058,'jlkq','jqi','kfdj','Iskander.456bahroun@gmail.com','gebes');
Insert into ISKANDER.FOURNISSEUR (ID,NUMTEL,NOM,QUALITE,CATEGORY,EMAIL,ADRESSE) values (15858,50587,'jlkqa','jqiee','kfdjde','Iskander.456bahroun@gmail.com','nabeul');
Insert into ISKANDER.FOURNISSEUR (ID,NUMTEL,NOM,QUALITE,CATEGORY,EMAIL,ADRESSE) values (1,505877,'adsie','hfos','goode','Iskander.456bahroun@gmail.com','jendouba');
Insert into ISKANDER.FOURNISSEUR (ID,NUMTEL,NOM,QUALITE,CATEGORY,EMAIL,ADRESSE) values (1587,696,'iskander','ke','fse','feza','tunis');
REM INSERTING into ISKANDER.EMPLOYES
SET DEFINE OFF;
Insert into ISKANDER.EMPLOYES (CIN,NOM,PRENOM,AGE,ROLE,SALAIRE) values (185,'iskander','bahroun',28,'roel',40);
REM INSERTING into ISKANDER.CLIENT
SET DEFINE OFF;
Insert into ISKANDER.CLIENT (CIN,NOM,PRENOM,TEL,ADRESSE) values (15,'aa','dd',16,'aa');
--------------------------------------------------------
--  DDL for Index PK_PRODUIT
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISKANDER"."PK_PRODUIT" ON "ISKANDER"."PRODUITCOSMETIQUE" ("NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OFFRE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISKANDER"."OFFRE_PK" ON "ISKANDER"."OFFRE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MATERIEL
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISKANDER"."PK_MATERIEL" ON "ISKANDER"."MATERIEL" ("REFERENCE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FOURNISSEUR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISKANDER"."FOURNISSEUR_PK" ON "ISKANDER"."FOURNISSEUR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYES
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISKANDER"."PK_EMPLOYES" ON "ISKANDER"."EMPLOYES" ("CIN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PRODUITCOSMETIQUE
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" ADD CONSTRAINT "PK_PRODUIT" PRIMARY KEY ("NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("MARQUE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("QUANTITE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("QRCODE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."PRODUITCOSMETIQUE" MODIFY ("NUM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OFFRE
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."OFFRE" ADD CONSTRAINT "OFFRE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ISKANDER"."OFFRE" MODIFY ("CIN_E" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."OFFRE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."OFFRE" MODIFY ("PRIX" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."OFFRE" MODIFY ("CODE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."MATERIEL" MODIFY ("ID_FOURNISEUR" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."MATERIEL" ADD CONSTRAINT "PK_MATERIEL" PRIMARY KEY ("REFERENCE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ISKANDER"."MATERIEL" MODIFY ("REFERENCE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."MATERIEL" MODIFY ("COULEUR" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."MATERIEL" MODIFY ("NOM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FOURNISSEUR
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("ADRESSE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" ADD CONSTRAINT "FOURNISSEUR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("QUALITE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("NUMTEL" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."FOURNISSEUR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYES
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."EMPLOYES" ADD CONSTRAINT "PK_EMPLOYES" PRIMARY KEY ("CIN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("SALAIRE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("ROLE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("AGE" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("PRENOM" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("NOM" NOT NULL ENABLE);
  ALTER TABLE "ISKANDER"."EMPLOYES" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."CLIENT" MODIFY ("CIN" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table OFFRE
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."OFFRE" ADD CONSTRAINT "FK_OFFRE" FOREIGN KEY ("CIN_E")
	  REFERENCES "ISKANDER"."EMPLOYES" ("CIN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MATERIEL
--------------------------------------------------------

  ALTER TABLE "ISKANDER"."MATERIEL" ADD CONSTRAINT "FK_FOURNISSEUR" FOREIGN KEY ("ID_FOURNISEUR")
	  REFERENCES "ISKANDER"."FOURNISSEUR" ("ID") ENABLE;
